 name: Test requirements installation

 on:
  workflow_dispatch:
  push:
    branches:
    - main
    - develop
    tags:
    - 'v*'

 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
   install_dependencies:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         container_image: ["fedora:34", "fedora:35", "fedora:36", "ubuntu:18.04", "ubuntu:20.04", "ubuntu:22.04"]
     container:
       image: ${{ matrix.container_image }}
     steps:
       - uses: actions/checkout@v3
       - name: Install sudo
         if: startsWith(matrix.container_image, 'fedora') == true
         run: yum update -y && yum install -y python3 python3-pip sudo
       - name: Install sudo
         if: startsWith(matrix.container_image, 'ubuntu') == true
         run: apt-get update  -qq && apt-get -qq install sudo
       - name: Install dependencies
         run: bash docs/source/_static/install_dependencies.sh
