 name: Test requirements installation

 on:
  workflow_dispatch:
  push:
    branches:
    - main
    - develop
    tags:
    - 'v*'

 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
   install_dependencies:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         container_image: ["fedora:34", "fedora:35", "fedora:36", "ubuntu:18.04", "ubuntu:20.04", "ubuntu:22.04"]
     container:
       image: ${{ matrix.container_image }}
     steps:
       - name: Hello from fedora
         if: startsWith(matrix.container_image, 'fedora') == true
         run: echo "Hello from fedora"
       - name: Hello from ubuntu
         if: startsWith(matrix.container_image, 'ubuntu') == true
         run: echo "Hello from ubuntu"
   
