 name: Test requirements installation

 on:
  workflow_dispatch:
  push:
    branches:
    - main
    - develop
    tags:
    - 'v*'

 ###################################
 ###################################

 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
   test-job:
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
         # The same array lives in test-windows.yml, so make any updates there too.
         test-group: [1, 2, 3]
#      strategy:
#        matrix:
#          image_name:
#            [
#              ubuntu:22.04,
#              ubuntu:20.04,
#            ]
     container:
        image: ubuntu:20.04
     steps:
       - name: Test one
         run: echo "Hello from this container!"
       - name: Test two
         run: echo "Hello from here ${{ matrix.test-group }} too!!!"
       - name: Test three
         run: cat /etc/*release*
