 name: Test requirements installation

 on:
  workflow_dispatch:
  push:
    branches:
    - main
    - develop
    tags:
    - 'v*'

 ###################################
 ###################################

 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
   test-job:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         image_name:
           [
             ubuntu:22.04,
             ubuntu:20.04
           ]
     container:
       - image: ${{ matrix.image_name }}
     steps:
       - name: Test one
         run: echo "Hello from this container!"
       - name: Test two
         run: echo "Hello from here too!!!"
       - name: Test three
         run: cat /etc/*release*
